version: "3.7"

services:
    app:
        container_name: church-music-laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: devlua/laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    nginx:
        container_name: church-music-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    mysql:
        container_name: church-music-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - laravel

    redis:
        container_name: church-music-redis
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge